### ISSUE TITLE
后台 - 分类页面

### ISSUE THREAD

**Issue by qfdk** [ninetysec/laravel-foodxl#3]
1. 编辑分类名称排序留空 无法保存

![2](https://user-images.githubusercontent.com/2404478/40282495-933f7a60-5c70-11e8-8091-2ea60d7cdddb.png)
2. 编辑状态，上级分类选择本分类，所有的分类会消失。如图 所示

- 分类名称 ->分类测试
- 上级分类 -> 分类测试
- 提交

分类列表为空
![3](https://user-images.githubusercontent.com/2404478/40282519-eb1631fc-5c70-11e8-868f-3458dfccb618.png)

**Comment by ninetysec** [comment]
完成

**Comment by qfdk** [comment]
OK
