### ISSUE TITLE
后台 - 添加产品

### ISSUE THREAD

**Issue by qfdk** [ninetysec/laravel-foodxl#4]
1. 无法删除产品 
2. 分类会自己变动， 问题未知。。
3. 无法添加图片
![4](https://user-images.githubusercontent.com/2404478/40282687-67b0f1dc-5c73-11e8-909d-1f414d4cea8c.png)
展示不要用input 因为这里的没发修改，要变成只读类型，否则需要用ajax 自动更改

**Comment by ninetysec** [comment]
完成，上架ajax操作暂缺
