### ISSUE TITLE
界面UI修改

### ISSUE THREAD

**Issue by qfdk** [ninetysec/laravel-foodxl#6]
晚上经过讨论，一下几点需要修改

- [x] 顶部导航栏可以做成 （分类，购物车，预定位置）
![daohang](https://user-images.githubusercontent.com/2404478/40324883-37cc8a72-5d3a-11e8-8702-d57fa0178838.png)
- [x] 顶部导航栏 （每个页面的导航栏都不一样，需要修改）
- [x] 点击添加菜品需要显示一个遮罩动画，并显示详情。

- 结账后订单详情 -->显示需要修改

**Comment by qfdk** [comment]
- [x] 顶部导航栏模板
<img width="409" alt="top" src="https://user-images.githubusercontent.com/2404478/40328995-71510602-5d48-11e8-9f7a-5492af9fc649.png">

- [ ]  分类详情页面
   - 例如点击 `菜单1`  cat?id=1 显示所有id为1 的菜单

**Comment by ninetysec** [comment]
已经将顶部导航栏做成单独文件，放在includes里面的nav文件，其他模板全部统一包含nav，同时将更新购物车数字函数写在全局footer里面，每次载入页面都更新数字，且添加删除产品也会刷新。
